Repository nspcc-dev/neofs-contract, pull requests merged in 2021-03, with the labels that each got.

#57 Feature/use readonly context
  alphabet/alphabet_contract.go
  audit/audit_contract.go
  balance/balance_contract.go
  container/container_contract.go
  neofs/neofs_contract.go
  neofsid/neofsid_contract.go
  netmap/netmap_contract.go
  proxy/proxy_contract.go
Labels: enhancement

#60 Use interop to create multi signature account
  netmap/netmap_contract.go
Labels: netmap

#62 Remove methods with notifications from safe list
  container/config.yml
  neofs/config.yml
Labels: bug

#63 Fix threshold number calculation
  common/ir.go
  neofs/neofs_contract.go
Labels: bug
